// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticatedUser.proto

package org.wso2.custom.authenticator.local.grpc;

public final class AuthenticatedUserOuterClass {
  private AuthenticatedUserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthenticatedUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthenticatedUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 serialVersionUID = 1;</code>
     */
    long getSerialVersionUID();

    /**
     * <code>string authenticatedSubjectIdentifier = 2;</code>
     */
    java.lang.String getAuthenticatedSubjectIdentifier();
    /**
     * <code>string authenticatedSubjectIdentifier = 2;</code>
     */
    com.google.protobuf.ByteString
        getAuthenticatedSubjectIdentifierBytes();

    /**
     * <code>string federatedIdPName = 3;</code>
     */
    java.lang.String getFederatedIdPName();
    /**
     * <code>string federatedIdPName = 3;</code>
     */
    com.google.protobuf.ByteString
        getFederatedIdPNameBytes();

    /**
     * <code>bool isFederatedUser = 4;</code>
     */
    boolean getIsFederatedUser();

    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> 
        getUserAttributesList();
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry getUserAttributes(int index);
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    int getUserAttributesCount();
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    java.util.List<? extends org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder> 
        getUserAttributesOrBuilderList();
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder getUserAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AuthenticatedUser}
   */
  public  static final class AuthenticatedUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuthenticatedUser)
      AuthenticatedUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthenticatedUser.newBuilder() to construct.
    private AuthenticatedUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthenticatedUser() {
      serialVersionUID_ = 0L;
      authenticatedSubjectIdentifier_ = "";
      federatedIdPName_ = "";
      isFederatedUser_ = false;
      userAttributes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticatedUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serialVersionUID_ = input.readSInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              authenticatedSubjectIdentifier_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              federatedIdPName_ = s;
              break;
            }
            case 32: {

              isFederatedUser_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                userAttributes_ = new java.util.ArrayList<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry>();
                mutable_bitField0_ |= 0x00000010;
              }
              userAttributes_.add(
                  input.readMessage(org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          userAttributes_ = java.util.Collections.unmodifiableList(userAttributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.internal_static_AuthenticatedUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.internal_static_AuthenticatedUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.class, org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.Builder.class);
    }

    private int bitField0_;
    public static final int SERIALVERSIONUID_FIELD_NUMBER = 1;
    private long serialVersionUID_;
    /**
     * <code>sint64 serialVersionUID = 1;</code>
     */
    public long getSerialVersionUID() {
      return serialVersionUID_;
    }

    public static final int AUTHENTICATEDSUBJECTIDENTIFIER_FIELD_NUMBER = 2;
    private volatile java.lang.Object authenticatedSubjectIdentifier_;
    /**
     * <code>string authenticatedSubjectIdentifier = 2;</code>
     */
    public java.lang.String getAuthenticatedSubjectIdentifier() {
      java.lang.Object ref = authenticatedSubjectIdentifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authenticatedSubjectIdentifier_ = s;
        return s;
      }
    }
    /**
     * <code>string authenticatedSubjectIdentifier = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAuthenticatedSubjectIdentifierBytes() {
      java.lang.Object ref = authenticatedSubjectIdentifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authenticatedSubjectIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEDERATEDIDPNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object federatedIdPName_;
    /**
     * <code>string federatedIdPName = 3;</code>
     */
    public java.lang.String getFederatedIdPName() {
      java.lang.Object ref = federatedIdPName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        federatedIdPName_ = s;
        return s;
      }
    }
    /**
     * <code>string federatedIdPName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFederatedIdPNameBytes() {
      java.lang.Object ref = federatedIdPName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        federatedIdPName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISFEDERATEDUSER_FIELD_NUMBER = 4;
    private boolean isFederatedUser_;
    /**
     * <code>bool isFederatedUser = 4;</code>
     */
    public boolean getIsFederatedUser() {
      return isFederatedUser_;
    }

    public static final int USERATTRIBUTES_FIELD_NUMBER = 5;
    private java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> userAttributes_;
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    public java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> getUserAttributesList() {
      return userAttributes_;
    }
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    public java.util.List<? extends org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder> 
        getUserAttributesOrBuilderList() {
      return userAttributes_;
    }
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    public int getUserAttributesCount() {
      return userAttributes_.size();
    }
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry getUserAttributes(int index) {
      return userAttributes_.get(index);
    }
    /**
     * <pre>
     *map&lt;ClaimMapping, string&gt; user= 6;
     * </pre>
     *
     * <code>repeated .MapEntry userAttributes = 5;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder getUserAttributesOrBuilder(
        int index) {
      return userAttributes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serialVersionUID_ != 0L) {
        output.writeSInt64(1, serialVersionUID_);
      }
      if (!getAuthenticatedSubjectIdentifierBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, authenticatedSubjectIdentifier_);
      }
      if (!getFederatedIdPNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, federatedIdPName_);
      }
      if (isFederatedUser_ != false) {
        output.writeBool(4, isFederatedUser_);
      }
      for (int i = 0; i < userAttributes_.size(); i++) {
        output.writeMessage(5, userAttributes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialVersionUID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, serialVersionUID_);
      }
      if (!getAuthenticatedSubjectIdentifierBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, authenticatedSubjectIdentifier_);
      }
      if (!getFederatedIdPNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, federatedIdPName_);
      }
      if (isFederatedUser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isFederatedUser_);
      }
      for (int i = 0; i < userAttributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, userAttributes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser)) {
        return super.equals(obj);
      }
      org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser other = (org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser) obj;

      boolean result = true;
      result = result && (getSerialVersionUID()
          == other.getSerialVersionUID());
      result = result && getAuthenticatedSubjectIdentifier()
          .equals(other.getAuthenticatedSubjectIdentifier());
      result = result && getFederatedIdPName()
          .equals(other.getFederatedIdPName());
      result = result && (getIsFederatedUser()
          == other.getIsFederatedUser());
      result = result && getUserAttributesList()
          .equals(other.getUserAttributesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALVERSIONUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSerialVersionUID());
      hash = (37 * hash) + AUTHENTICATEDSUBJECTIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getAuthenticatedSubjectIdentifier().hashCode();
      hash = (37 * hash) + FEDERATEDIDPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFederatedIdPName().hashCode();
      hash = (37 * hash) + ISFEDERATEDUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFederatedUser());
      if (getUserAttributesCount() > 0) {
        hash = (37 * hash) + USERATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + getUserAttributesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthenticatedUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthenticatedUser)
        org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.internal_static_AuthenticatedUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.internal_static_AuthenticatedUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.class, org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.Builder.class);
      }

      // Construct using org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserAttributesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serialVersionUID_ = 0L;

        authenticatedSubjectIdentifier_ = "";

        federatedIdPName_ = "";

        isFederatedUser_ = false;

        if (userAttributesBuilder_ == null) {
          userAttributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          userAttributesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.internal_static_AuthenticatedUser_descriptor;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser getDefaultInstanceForType() {
        return org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser build() {
        org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser buildPartial() {
        org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser result = new org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.serialVersionUID_ = serialVersionUID_;
        result.authenticatedSubjectIdentifier_ = authenticatedSubjectIdentifier_;
        result.federatedIdPName_ = federatedIdPName_;
        result.isFederatedUser_ = isFederatedUser_;
        if (userAttributesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            userAttributes_ = java.util.Collections.unmodifiableList(userAttributes_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.userAttributes_ = userAttributes_;
        } else {
          result.userAttributes_ = userAttributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser) {
          return mergeFrom((org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser other) {
        if (other == org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser.getDefaultInstance()) return this;
        if (other.getSerialVersionUID() != 0L) {
          setSerialVersionUID(other.getSerialVersionUID());
        }
        if (!other.getAuthenticatedSubjectIdentifier().isEmpty()) {
          authenticatedSubjectIdentifier_ = other.authenticatedSubjectIdentifier_;
          onChanged();
        }
        if (!other.getFederatedIdPName().isEmpty()) {
          federatedIdPName_ = other.federatedIdPName_;
          onChanged();
        }
        if (other.getIsFederatedUser() != false) {
          setIsFederatedUser(other.getIsFederatedUser());
        }
        if (userAttributesBuilder_ == null) {
          if (!other.userAttributes_.isEmpty()) {
            if (userAttributes_.isEmpty()) {
              userAttributes_ = other.userAttributes_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureUserAttributesIsMutable();
              userAttributes_.addAll(other.userAttributes_);
            }
            onChanged();
          }
        } else {
          if (!other.userAttributes_.isEmpty()) {
            if (userAttributesBuilder_.isEmpty()) {
              userAttributesBuilder_.dispose();
              userAttributesBuilder_ = null;
              userAttributes_ = other.userAttributes_;
              bitField0_ = (bitField0_ & ~0x00000010);
              userAttributesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserAttributesFieldBuilder() : null;
            } else {
              userAttributesBuilder_.addAllMessages(other.userAttributes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long serialVersionUID_ ;
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public long getSerialVersionUID() {
        return serialVersionUID_;
      }
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public Builder setSerialVersionUID(long value) {
        
        serialVersionUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public Builder clearSerialVersionUID() {
        
        serialVersionUID_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object authenticatedSubjectIdentifier_ = "";
      /**
       * <code>string authenticatedSubjectIdentifier = 2;</code>
       */
      public java.lang.String getAuthenticatedSubjectIdentifier() {
        java.lang.Object ref = authenticatedSubjectIdentifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authenticatedSubjectIdentifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAuthenticatedSubjectIdentifierBytes() {
        java.lang.Object ref = authenticatedSubjectIdentifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authenticatedSubjectIdentifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 2;</code>
       */
      public Builder setAuthenticatedSubjectIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authenticatedSubjectIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 2;</code>
       */
      public Builder clearAuthenticatedSubjectIdentifier() {
        
        authenticatedSubjectIdentifier_ = getDefaultInstance().getAuthenticatedSubjectIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 2;</code>
       */
      public Builder setAuthenticatedSubjectIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authenticatedSubjectIdentifier_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object federatedIdPName_ = "";
      /**
       * <code>string federatedIdPName = 3;</code>
       */
      public java.lang.String getFederatedIdPName() {
        java.lang.Object ref = federatedIdPName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          federatedIdPName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string federatedIdPName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFederatedIdPNameBytes() {
        java.lang.Object ref = federatedIdPName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          federatedIdPName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string federatedIdPName = 3;</code>
       */
      public Builder setFederatedIdPName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        federatedIdPName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string federatedIdPName = 3;</code>
       */
      public Builder clearFederatedIdPName() {
        
        federatedIdPName_ = getDefaultInstance().getFederatedIdPName();
        onChanged();
        return this;
      }
      /**
       * <code>string federatedIdPName = 3;</code>
       */
      public Builder setFederatedIdPNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        federatedIdPName_ = value;
        onChanged();
        return this;
      }

      private boolean isFederatedUser_ ;
      /**
       * <code>bool isFederatedUser = 4;</code>
       */
      public boolean getIsFederatedUser() {
        return isFederatedUser_;
      }
      /**
       * <code>bool isFederatedUser = 4;</code>
       */
      public Builder setIsFederatedUser(boolean value) {
        
        isFederatedUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFederatedUser = 4;</code>
       */
      public Builder clearIsFederatedUser() {
        
        isFederatedUser_ = false;
        onChanged();
        return this;
      }

      private java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> userAttributes_ =
        java.util.Collections.emptyList();
      private void ensureUserAttributesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          userAttributes_ = new java.util.ArrayList<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry>(userAttributes_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder> userAttributesBuilder_;

      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> getUserAttributesList() {
        if (userAttributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userAttributes_);
        } else {
          return userAttributesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public int getUserAttributesCount() {
        if (userAttributesBuilder_ == null) {
          return userAttributes_.size();
        } else {
          return userAttributesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry getUserAttributes(int index) {
        if (userAttributesBuilder_ == null) {
          return userAttributes_.get(index);
        } else {
          return userAttributesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder setUserAttributes(
          int index, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry value) {
        if (userAttributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserAttributesIsMutable();
          userAttributes_.set(index, value);
          onChanged();
        } else {
          userAttributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder setUserAttributes(
          int index, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder builderForValue) {
        if (userAttributesBuilder_ == null) {
          ensureUserAttributesIsMutable();
          userAttributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          userAttributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder addUserAttributes(org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry value) {
        if (userAttributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserAttributesIsMutable();
          userAttributes_.add(value);
          onChanged();
        } else {
          userAttributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder addUserAttributes(
          int index, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry value) {
        if (userAttributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserAttributesIsMutable();
          userAttributes_.add(index, value);
          onChanged();
        } else {
          userAttributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder addUserAttributes(
          org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder builderForValue) {
        if (userAttributesBuilder_ == null) {
          ensureUserAttributesIsMutable();
          userAttributes_.add(builderForValue.build());
          onChanged();
        } else {
          userAttributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder addUserAttributes(
          int index, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder builderForValue) {
        if (userAttributesBuilder_ == null) {
          ensureUserAttributesIsMutable();
          userAttributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          userAttributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder addAllUserAttributes(
          java.lang.Iterable<? extends org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry> values) {
        if (userAttributesBuilder_ == null) {
          ensureUserAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userAttributes_);
          onChanged();
        } else {
          userAttributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder clearUserAttributes() {
        if (userAttributesBuilder_ == null) {
          userAttributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          userAttributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public Builder removeUserAttributes(int index) {
        if (userAttributesBuilder_ == null) {
          ensureUserAttributesIsMutable();
          userAttributes_.remove(index);
          onChanged();
        } else {
          userAttributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder getUserAttributesBuilder(
          int index) {
        return getUserAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder getUserAttributesOrBuilder(
          int index) {
        if (userAttributesBuilder_ == null) {
          return userAttributes_.get(index);  } else {
          return userAttributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public java.util.List<? extends org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder> 
           getUserAttributesOrBuilderList() {
        if (userAttributesBuilder_ != null) {
          return userAttributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userAttributes_);
        }
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder addUserAttributesBuilder() {
        return getUserAttributesFieldBuilder().addBuilder(
            org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder addUserAttributesBuilder(
          int index) {
        return getUserAttributesFieldBuilder().addBuilder(
            index, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       *map&lt;ClaimMapping, string&gt; user= 6;
       * </pre>
       *
       * <code>repeated .MapEntry userAttributes = 5;</code>
       */
      public java.util.List<org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder> 
           getUserAttributesBuilderList() {
        return getUserAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder> 
          getUserAttributesFieldBuilder() {
        if (userAttributesBuilder_ == null) {
          userAttributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntry.Builder, org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.MapEntryOrBuilder>(
                  userAttributes_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          userAttributes_ = null;
        }
        return userAttributesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuthenticatedUser)
    }

    // @@protoc_insertion_point(class_scope:AuthenticatedUser)
    private static final org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser();
    }

    public static org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthenticatedUser>
        PARSER = new com.google.protobuf.AbstractParser<AuthenticatedUser>() {
      @java.lang.Override
      public AuthenticatedUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticatedUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthenticatedUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticatedUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.custom.authenticator.local.grpc.AuthenticatedUserOuterClass.AuthenticatedUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticatedUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticatedUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AuthenticatedUser.proto\032\016MapEntry.prot" +
      "o\032\022ClaimMapping.proto\"\253\001\n\021AuthenticatedU" +
      "ser\022\030\n\020serialVersionUID\030\001 \001(\022\022&\n\036authent" +
      "icatedSubjectIdentifier\030\002 \001(\t\022\030\n\020federat" +
      "edIdPName\030\003 \001(\t\022\027\n\017isFederatedUser\030\004 \001(\010" +
      "\022!\n\016userAttributes\030\005 \003(\0132\t.MapEntryB*\n(o" +
      "rg.wso2.custom.authenticator.local.grpcb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.getDescriptor(),
          org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.getDescriptor(),
        }, assigner);
    internal_static_AuthenticatedUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthenticatedUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticatedUser_descriptor,
        new java.lang.String[] { "SerialVersionUID", "AuthenticatedSubjectIdentifier", "FederatedIdPName", "IsFederatedUser", "UserAttributes", });
    org.wso2.custom.authenticator.local.grpc.MapEntryOuterClass.getDescriptor();
    org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
