// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Claim.proto

package org.wso2.custom.authenticator.local.grpc;

public final class ClaimOuterClass {
  private ClaimOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClaimOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Claim)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 serialVersionUID = 1;</code>
     */
    long getSerialVersionUID();

    /**
     * <code>string claimUri = 2;</code>
     */
    java.lang.String getClaimUri();
    /**
     * <code>string claimUri = 2;</code>
     */
    com.google.protobuf.ByteString
        getClaimUriBytes();

    /**
     * <code>int32 claimId = 3;</code>
     */
    int getClaimId();
  }
  /**
   * Protobuf type {@code Claim}
   */
  public  static final class Claim extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Claim)
      ClaimOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Claim.newBuilder() to construct.
    private Claim(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Claim() {
      serialVersionUID_ = 0L;
      claimUri_ = "";
      claimId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Claim(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serialVersionUID_ = input.readSInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              claimUri_ = s;
              break;
            }
            case 24: {

              claimId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.internal_static_Claim_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.internal_static_Claim_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.class, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder.class);
    }

    public static final int SERIALVERSIONUID_FIELD_NUMBER = 1;
    private long serialVersionUID_;
    /**
     * <code>sint64 serialVersionUID = 1;</code>
     */
    public long getSerialVersionUID() {
      return serialVersionUID_;
    }

    public static final int CLAIMURI_FIELD_NUMBER = 2;
    private volatile java.lang.Object claimUri_;
    /**
     * <code>string claimUri = 2;</code>
     */
    public java.lang.String getClaimUri() {
      java.lang.Object ref = claimUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        claimUri_ = s;
        return s;
      }
    }
    /**
     * <code>string claimUri = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClaimUriBytes() {
      java.lang.Object ref = claimUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        claimUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLAIMID_FIELD_NUMBER = 3;
    private int claimId_;
    /**
     * <code>int32 claimId = 3;</code>
     */
    public int getClaimId() {
      return claimId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serialVersionUID_ != 0L) {
        output.writeSInt64(1, serialVersionUID_);
      }
      if (!getClaimUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, claimUri_);
      }
      if (claimId_ != 0) {
        output.writeInt32(3, claimId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialVersionUID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, serialVersionUID_);
      }
      if (!getClaimUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, claimUri_);
      }
      if (claimId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, claimId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim)) {
        return super.equals(obj);
      }
      org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim other = (org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim) obj;

      boolean result = true;
      result = result && (getSerialVersionUID()
          == other.getSerialVersionUID());
      result = result && getClaimUri()
          .equals(other.getClaimUri());
      result = result && (getClaimId()
          == other.getClaimId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALVERSIONUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSerialVersionUID());
      hash = (37 * hash) + CLAIMURI_FIELD_NUMBER;
      hash = (53 * hash) + getClaimUri().hashCode();
      hash = (37 * hash) + CLAIMID_FIELD_NUMBER;
      hash = (53 * hash) + getClaimId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Claim}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Claim)
        org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.internal_static_Claim_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.internal_static_Claim_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.class, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder.class);
      }

      // Construct using org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serialVersionUID_ = 0L;

        claimUri_ = "";

        claimId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.internal_static_Claim_descriptor;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getDefaultInstanceForType() {
        return org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim build() {
        org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim buildPartial() {
        org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim result = new org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim(this);
        result.serialVersionUID_ = serialVersionUID_;
        result.claimUri_ = claimUri_;
        result.claimId_ = claimId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim) {
          return mergeFrom((org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim other) {
        if (other == org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance()) return this;
        if (other.getSerialVersionUID() != 0L) {
          setSerialVersionUID(other.getSerialVersionUID());
        }
        if (!other.getClaimUri().isEmpty()) {
          claimUri_ = other.claimUri_;
          onChanged();
        }
        if (other.getClaimId() != 0) {
          setClaimId(other.getClaimId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long serialVersionUID_ ;
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public long getSerialVersionUID() {
        return serialVersionUID_;
      }
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public Builder setSerialVersionUID(long value) {
        
        serialVersionUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 serialVersionUID = 1;</code>
       */
      public Builder clearSerialVersionUID() {
        
        serialVersionUID_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object claimUri_ = "";
      /**
       * <code>string claimUri = 2;</code>
       */
      public java.lang.String getClaimUri() {
        java.lang.Object ref = claimUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          claimUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string claimUri = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClaimUriBytes() {
        java.lang.Object ref = claimUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          claimUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string claimUri = 2;</code>
       */
      public Builder setClaimUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        claimUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string claimUri = 2;</code>
       */
      public Builder clearClaimUri() {
        
        claimUri_ = getDefaultInstance().getClaimUri();
        onChanged();
        return this;
      }
      /**
       * <code>string claimUri = 2;</code>
       */
      public Builder setClaimUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        claimUri_ = value;
        onChanged();
        return this;
      }

      private int claimId_ ;
      /**
       * <code>int32 claimId = 3;</code>
       */
      public int getClaimId() {
        return claimId_;
      }
      /**
       * <code>int32 claimId = 3;</code>
       */
      public Builder setClaimId(int value) {
        
        claimId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 claimId = 3;</code>
       */
      public Builder clearClaimId() {
        
        claimId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Claim)
    }

    // @@protoc_insertion_point(class_scope:Claim)
    private static final org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim();
    }

    public static org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Claim>
        PARSER = new com.google.protobuf.AbstractParser<Claim>() {
      @java.lang.Override
      public Claim parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Claim(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Claim> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Claim> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Claim_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Claim_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Claim.proto\"D\n\005Claim\022\030\n\020serialVersionU" +
      "ID\030\001 \001(\022\022\020\n\010claimUri\030\002 \001(\t\022\017\n\007claimId\030\003 " +
      "\001(\005B*\n(org.wso2.custom.authenticator.loc" +
      "al.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Claim_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Claim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Claim_descriptor,
        new java.lang.String[] { "SerialVersionUID", "ClaimUri", "ClaimId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
