// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClaimMapping.proto

package org.wso2.custom.authenticator.local.grpc;

public final class ClaimMappingOuterClass {
  private ClaimMappingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClaimMappingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClaimMapping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 serialVersionUID = 1;</code>
     */
    int getSerialVersionUID();

    /**
     * <code>.Claim localClaim = 2;</code>
     */
    boolean hasLocalClaim();
    /**
     * <code>.Claim localClaim = 2;</code>
     */
    org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getLocalClaim();
    /**
     * <code>.Claim localClaim = 2;</code>
     */
    org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getLocalClaimOrBuilder();

    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    boolean hasRemoteClaim();
    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getRemoteClaim();
    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getRemoteClaimOrBuilder();

    /**
     * <code>string defaultValue = 4;</code>
     */
    java.lang.String getDefaultValue();
    /**
     * <code>string defaultValue = 4;</code>
     */
    com.google.protobuf.ByteString
        getDefaultValueBytes();

    /**
     * <code>bool requested = 5;</code>
     */
    boolean getRequested();
  }
  /**
   * Protobuf type {@code ClaimMapping}
   */
  public  static final class ClaimMapping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClaimMapping)
      ClaimMappingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClaimMapping.newBuilder() to construct.
    private ClaimMapping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClaimMapping() {
      serialVersionUID_ = 0;
      defaultValue_ = "";
      requested_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClaimMapping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serialVersionUID_ = input.readSInt32();
              break;
            }
            case 18: {
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder subBuilder = null;
              if (localClaim_ != null) {
                subBuilder = localClaim_.toBuilder();
              }
              localClaim_ = input.readMessage(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(localClaim_);
                localClaim_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder subBuilder = null;
              if (remoteClaim_ != null) {
                subBuilder = remoteClaim_.toBuilder();
              }
              remoteClaim_ = input.readMessage(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(remoteClaim_);
                remoteClaim_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              defaultValue_ = s;
              break;
            }
            case 40: {

              requested_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.internal_static_ClaimMapping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.internal_static_ClaimMapping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.class, org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.Builder.class);
    }

    public static final int SERIALVERSIONUID_FIELD_NUMBER = 1;
    private int serialVersionUID_;
    /**
     * <code>sint32 serialVersionUID = 1;</code>
     */
    public int getSerialVersionUID() {
      return serialVersionUID_;
    }

    public static final int LOCALCLAIM_FIELD_NUMBER = 2;
    private org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim localClaim_;
    /**
     * <code>.Claim localClaim = 2;</code>
     */
    public boolean hasLocalClaim() {
      return localClaim_ != null;
    }
    /**
     * <code>.Claim localClaim = 2;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getLocalClaim() {
      return localClaim_ == null ? org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : localClaim_;
    }
    /**
     * <code>.Claim localClaim = 2;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getLocalClaimOrBuilder() {
      return getLocalClaim();
    }

    public static final int REMOTECLAIM_FIELD_NUMBER = 3;
    private org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim remoteClaim_;
    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    public boolean hasRemoteClaim() {
      return remoteClaim_ != null;
    }
    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getRemoteClaim() {
      return remoteClaim_ == null ? org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : remoteClaim_;
    }
    /**
     * <code>.Claim remoteClaim = 3;</code>
     */
    public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getRemoteClaimOrBuilder() {
      return getRemoteClaim();
    }

    public static final int DEFAULTVALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object defaultValue_;
    /**
     * <code>string defaultValue = 4;</code>
     */
    public java.lang.String getDefaultValue() {
      java.lang.Object ref = defaultValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultValue_ = s;
        return s;
      }
    }
    /**
     * <code>string defaultValue = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      java.lang.Object ref = defaultValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTED_FIELD_NUMBER = 5;
    private boolean requested_;
    /**
     * <code>bool requested = 5;</code>
     */
    public boolean getRequested() {
      return requested_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serialVersionUID_ != 0) {
        output.writeSInt32(1, serialVersionUID_);
      }
      if (localClaim_ != null) {
        output.writeMessage(2, getLocalClaim());
      }
      if (remoteClaim_ != null) {
        output.writeMessage(3, getRemoteClaim());
      }
      if (!getDefaultValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, defaultValue_);
      }
      if (requested_ != false) {
        output.writeBool(5, requested_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialVersionUID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, serialVersionUID_);
      }
      if (localClaim_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocalClaim());
      }
      if (remoteClaim_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRemoteClaim());
      }
      if (!getDefaultValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, defaultValue_);
      }
      if (requested_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, requested_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping)) {
        return super.equals(obj);
      }
      org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping other = (org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping) obj;

      boolean result = true;
      result = result && (getSerialVersionUID()
          == other.getSerialVersionUID());
      result = result && (hasLocalClaim() == other.hasLocalClaim());
      if (hasLocalClaim()) {
        result = result && getLocalClaim()
            .equals(other.getLocalClaim());
      }
      result = result && (hasRemoteClaim() == other.hasRemoteClaim());
      if (hasRemoteClaim()) {
        result = result && getRemoteClaim()
            .equals(other.getRemoteClaim());
      }
      result = result && getDefaultValue()
          .equals(other.getDefaultValue());
      result = result && (getRequested()
          == other.getRequested());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALVERSIONUID_FIELD_NUMBER;
      hash = (53 * hash) + getSerialVersionUID();
      if (hasLocalClaim()) {
        hash = (37 * hash) + LOCALCLAIM_FIELD_NUMBER;
        hash = (53 * hash) + getLocalClaim().hashCode();
      }
      if (hasRemoteClaim()) {
        hash = (37 * hash) + REMOTECLAIM_FIELD_NUMBER;
        hash = (53 * hash) + getRemoteClaim().hashCode();
      }
      hash = (37 * hash) + DEFAULTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultValue().hashCode();
      hash = (37 * hash) + REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequested());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClaimMapping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClaimMapping)
        org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMappingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.internal_static_ClaimMapping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.internal_static_ClaimMapping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.class, org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.Builder.class);
      }

      // Construct using org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serialVersionUID_ = 0;

        if (localClaimBuilder_ == null) {
          localClaim_ = null;
        } else {
          localClaim_ = null;
          localClaimBuilder_ = null;
        }
        if (remoteClaimBuilder_ == null) {
          remoteClaim_ = null;
        } else {
          remoteClaim_ = null;
          remoteClaimBuilder_ = null;
        }
        defaultValue_ = "";

        requested_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.internal_static_ClaimMapping_descriptor;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping getDefaultInstanceForType() {
        return org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping build() {
        org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping buildPartial() {
        org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping result = new org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping(this);
        result.serialVersionUID_ = serialVersionUID_;
        if (localClaimBuilder_ == null) {
          result.localClaim_ = localClaim_;
        } else {
          result.localClaim_ = localClaimBuilder_.build();
        }
        if (remoteClaimBuilder_ == null) {
          result.remoteClaim_ = remoteClaim_;
        } else {
          result.remoteClaim_ = remoteClaimBuilder_.build();
        }
        result.defaultValue_ = defaultValue_;
        result.requested_ = requested_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping) {
          return mergeFrom((org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping other) {
        if (other == org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping.getDefaultInstance()) return this;
        if (other.getSerialVersionUID() != 0) {
          setSerialVersionUID(other.getSerialVersionUID());
        }
        if (other.hasLocalClaim()) {
          mergeLocalClaim(other.getLocalClaim());
        }
        if (other.hasRemoteClaim()) {
          mergeRemoteClaim(other.getRemoteClaim());
        }
        if (!other.getDefaultValue().isEmpty()) {
          defaultValue_ = other.defaultValue_;
          onChanged();
        }
        if (other.getRequested() != false) {
          setRequested(other.getRequested());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serialVersionUID_ ;
      /**
       * <code>sint32 serialVersionUID = 1;</code>
       */
      public int getSerialVersionUID() {
        return serialVersionUID_;
      }
      /**
       * <code>sint32 serialVersionUID = 1;</code>
       */
      public Builder setSerialVersionUID(int value) {
        
        serialVersionUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 serialVersionUID = 1;</code>
       */
      public Builder clearSerialVersionUID() {
        
        serialVersionUID_ = 0;
        onChanged();
        return this;
      }

      private org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim localClaim_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder> localClaimBuilder_;
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public boolean hasLocalClaim() {
        return localClaimBuilder_ != null || localClaim_ != null;
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getLocalClaim() {
        if (localClaimBuilder_ == null) {
          return localClaim_ == null ? org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : localClaim_;
        } else {
          return localClaimBuilder_.getMessage();
        }
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public Builder setLocalClaim(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim value) {
        if (localClaimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          localClaim_ = value;
          onChanged();
        } else {
          localClaimBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public Builder setLocalClaim(
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder builderForValue) {
        if (localClaimBuilder_ == null) {
          localClaim_ = builderForValue.build();
          onChanged();
        } else {
          localClaimBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public Builder mergeLocalClaim(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim value) {
        if (localClaimBuilder_ == null) {
          if (localClaim_ != null) {
            localClaim_ =
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.newBuilder(localClaim_).mergeFrom(value).buildPartial();
          } else {
            localClaim_ = value;
          }
          onChanged();
        } else {
          localClaimBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public Builder clearLocalClaim() {
        if (localClaimBuilder_ == null) {
          localClaim_ = null;
          onChanged();
        } else {
          localClaim_ = null;
          localClaimBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder getLocalClaimBuilder() {
        
        onChanged();
        return getLocalClaimFieldBuilder().getBuilder();
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getLocalClaimOrBuilder() {
        if (localClaimBuilder_ != null) {
          return localClaimBuilder_.getMessageOrBuilder();
        } else {
          return localClaim_ == null ?
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : localClaim_;
        }
      }
      /**
       * <code>.Claim localClaim = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder> 
          getLocalClaimFieldBuilder() {
        if (localClaimBuilder_ == null) {
          localClaimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder>(
                  getLocalClaim(),
                  getParentForChildren(),
                  isClean());
          localClaim_ = null;
        }
        return localClaimBuilder_;
      }

      private org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim remoteClaim_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder> remoteClaimBuilder_;
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public boolean hasRemoteClaim() {
        return remoteClaimBuilder_ != null || remoteClaim_ != null;
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim getRemoteClaim() {
        if (remoteClaimBuilder_ == null) {
          return remoteClaim_ == null ? org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : remoteClaim_;
        } else {
          return remoteClaimBuilder_.getMessage();
        }
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public Builder setRemoteClaim(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim value) {
        if (remoteClaimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          remoteClaim_ = value;
          onChanged();
        } else {
          remoteClaimBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public Builder setRemoteClaim(
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder builderForValue) {
        if (remoteClaimBuilder_ == null) {
          remoteClaim_ = builderForValue.build();
          onChanged();
        } else {
          remoteClaimBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public Builder mergeRemoteClaim(org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim value) {
        if (remoteClaimBuilder_ == null) {
          if (remoteClaim_ != null) {
            remoteClaim_ =
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.newBuilder(remoteClaim_).mergeFrom(value).buildPartial();
          } else {
            remoteClaim_ = value;
          }
          onChanged();
        } else {
          remoteClaimBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public Builder clearRemoteClaim() {
        if (remoteClaimBuilder_ == null) {
          remoteClaim_ = null;
          onChanged();
        } else {
          remoteClaim_ = null;
          remoteClaimBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder getRemoteClaimBuilder() {
        
        onChanged();
        return getRemoteClaimFieldBuilder().getBuilder();
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      public org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder getRemoteClaimOrBuilder() {
        if (remoteClaimBuilder_ != null) {
          return remoteClaimBuilder_.getMessageOrBuilder();
        } else {
          return remoteClaim_ == null ?
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.getDefaultInstance() : remoteClaim_;
        }
      }
      /**
       * <code>.Claim remoteClaim = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder> 
          getRemoteClaimFieldBuilder() {
        if (remoteClaimBuilder_ == null) {
          remoteClaimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.Claim.Builder, org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.ClaimOrBuilder>(
                  getRemoteClaim(),
                  getParentForChildren(),
                  isClean());
          remoteClaim_ = null;
        }
        return remoteClaimBuilder_;
      }

      private java.lang.Object defaultValue_ = "";
      /**
       * <code>string defaultValue = 4;</code>
       */
      public java.lang.String getDefaultValue() {
        java.lang.Object ref = defaultValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          defaultValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string defaultValue = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDefaultValueBytes() {
        java.lang.Object ref = defaultValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          defaultValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string defaultValue = 4;</code>
       */
      public Builder setDefaultValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        defaultValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string defaultValue = 4;</code>
       */
      public Builder clearDefaultValue() {
        
        defaultValue_ = getDefaultInstance().getDefaultValue();
        onChanged();
        return this;
      }
      /**
       * <code>string defaultValue = 4;</code>
       */
      public Builder setDefaultValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        defaultValue_ = value;
        onChanged();
        return this;
      }

      private boolean requested_ ;
      /**
       * <code>bool requested = 5;</code>
       */
      public boolean getRequested() {
        return requested_;
      }
      /**
       * <code>bool requested = 5;</code>
       */
      public Builder setRequested(boolean value) {
        
        requested_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool requested = 5;</code>
       */
      public Builder clearRequested() {
        
        requested_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClaimMapping)
    }

    // @@protoc_insertion_point(class_scope:ClaimMapping)
    private static final org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping();
    }

    public static org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClaimMapping>
        PARSER = new com.google.protobuf.AbstractParser<ClaimMapping>() {
      @java.lang.Override
      public ClaimMapping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClaimMapping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClaimMapping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClaimMapping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.custom.authenticator.local.grpc.ClaimMappingOuterClass.ClaimMapping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClaimMapping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClaimMapping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ClaimMapping.proto\032\013Claim.proto\"\212\001\n\014Cl" +
      "aimMapping\022\030\n\020serialVersionUID\030\001 \001(\021\022\032\n\n" +
      "localClaim\030\002 \001(\0132\006.Claim\022\033\n\013remoteClaim\030" +
      "\003 \001(\0132\006.Claim\022\024\n\014defaultValue\030\004 \001(\t\022\021\n\tr" +
      "equested\030\005 \001(\010B*\n(org.wso2.custom.authen" +
      "ticator.local.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.getDescriptor(),
        }, assigner);
    internal_static_ClaimMapping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClaimMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClaimMapping_descriptor,
        new java.lang.String[] { "SerialVersionUID", "LocalClaim", "RemoteClaim", "DefaultValue", "Requested", });
    org.wso2.custom.authenticator.local.grpc.ClaimOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
