// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.wso2.custom.authenticator.local.grpc;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string authenticatedSubjectIdentifier = 1;</code>
     */
    java.lang.String getAuthenticatedSubjectIdentifier();
    /**
     * <code>string authenticatedSubjectIdentifier = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthenticatedSubjectIdentifierBytes();

    /**
     * <code>string federatedIdPName = 2;</code>
     */
    java.lang.String getFederatedIdPName();
    /**
     * <code>string federatedIdPName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFederatedIdPNameBytes();

    /**
     * <code>bool isFederatedUser = 3;</code>
     */
    boolean getIsFederatedUser();

    /**
     * <code>string tenantDomain = 4;</code>
     */
    java.lang.String getTenantDomain();
    /**
     * <code>string tenantDomain = 4;</code>
     */
    com.google.protobuf.ByteString
        getTenantDomainBytes();

    /**
     * <code>string userStoreDomain = 5;</code>
     */
    java.lang.String getUserStoreDomain();
    /**
     * <code>string userStoreDomain = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserStoreDomainBytes();

    /**
     * <code>string userName = 6;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 6;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      authenticatedSubjectIdentifier_ = "";
      federatedIdPName_ = "";
      isFederatedUser_ = false;
      tenantDomain_ = "";
      userStoreDomain_ = "";
      userName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              authenticatedSubjectIdentifier_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              federatedIdPName_ = s;
              break;
            }
            case 24: {

              isFederatedUser_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              tenantDomain_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userStoreDomain_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.class, org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.Builder.class);
    }

    public static final int AUTHENTICATEDSUBJECTIDENTIFIER_FIELD_NUMBER = 1;
    private volatile java.lang.Object authenticatedSubjectIdentifier_;
    /**
     * <code>string authenticatedSubjectIdentifier = 1;</code>
     */
    public java.lang.String getAuthenticatedSubjectIdentifier() {
      java.lang.Object ref = authenticatedSubjectIdentifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authenticatedSubjectIdentifier_ = s;
        return s;
      }
    }
    /**
     * <code>string authenticatedSubjectIdentifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthenticatedSubjectIdentifierBytes() {
      java.lang.Object ref = authenticatedSubjectIdentifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authenticatedSubjectIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEDERATEDIDPNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object federatedIdPName_;
    /**
     * <code>string federatedIdPName = 2;</code>
     */
    public java.lang.String getFederatedIdPName() {
      java.lang.Object ref = federatedIdPName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        federatedIdPName_ = s;
        return s;
      }
    }
    /**
     * <code>string federatedIdPName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFederatedIdPNameBytes() {
      java.lang.Object ref = federatedIdPName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        federatedIdPName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISFEDERATEDUSER_FIELD_NUMBER = 3;
    private boolean isFederatedUser_;
    /**
     * <code>bool isFederatedUser = 3;</code>
     */
    public boolean getIsFederatedUser() {
      return isFederatedUser_;
    }

    public static final int TENANTDOMAIN_FIELD_NUMBER = 4;
    private volatile java.lang.Object tenantDomain_;
    /**
     * <code>string tenantDomain = 4;</code>
     */
    public java.lang.String getTenantDomain() {
      java.lang.Object ref = tenantDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantDomain_ = s;
        return s;
      }
    }
    /**
     * <code>string tenantDomain = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTenantDomainBytes() {
      java.lang.Object ref = tenantDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERSTOREDOMAIN_FIELD_NUMBER = 5;
    private volatile java.lang.Object userStoreDomain_;
    /**
     * <code>string userStoreDomain = 5;</code>
     */
    public java.lang.String getUserStoreDomain() {
      java.lang.Object ref = userStoreDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userStoreDomain_ = s;
        return s;
      }
    }
    /**
     * <code>string userStoreDomain = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserStoreDomainBytes() {
      java.lang.Object ref = userStoreDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userStoreDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 6;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAuthenticatedSubjectIdentifierBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authenticatedSubjectIdentifier_);
      }
      if (!getFederatedIdPNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, federatedIdPName_);
      }
      if (isFederatedUser_ != false) {
        output.writeBool(3, isFederatedUser_);
      }
      if (!getTenantDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tenantDomain_);
      }
      if (!getUserStoreDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userStoreDomain_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAuthenticatedSubjectIdentifierBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authenticatedSubjectIdentifier_);
      }
      if (!getFederatedIdPNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, federatedIdPName_);
      }
      if (isFederatedUser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFederatedUser_);
      }
      if (!getTenantDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tenantDomain_);
      }
      if (!getUserStoreDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userStoreDomain_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.custom.authenticator.local.grpc.UserOuterClass.User)) {
        return super.equals(obj);
      }
      org.wso2.custom.authenticator.local.grpc.UserOuterClass.User other = (org.wso2.custom.authenticator.local.grpc.UserOuterClass.User) obj;

      boolean result = true;
      result = result && getAuthenticatedSubjectIdentifier()
          .equals(other.getAuthenticatedSubjectIdentifier());
      result = result && getFederatedIdPName()
          .equals(other.getFederatedIdPName());
      result = result && (getIsFederatedUser()
          == other.getIsFederatedUser());
      result = result && getTenantDomain()
          .equals(other.getTenantDomain());
      result = result && getUserStoreDomain()
          .equals(other.getUserStoreDomain());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHENTICATEDSUBJECTIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getAuthenticatedSubjectIdentifier().hashCode();
      hash = (37 * hash) + FEDERATEDIDPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFederatedIdPName().hashCode();
      hash = (37 * hash) + ISFEDERATEDUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFederatedUser());
      hash = (37 * hash) + TENANTDOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getTenantDomain().hashCode();
      hash = (37 * hash) + USERSTOREDOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getUserStoreDomain().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.custom.authenticator.local.grpc.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.class, org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.Builder.class);
      }

      // Construct using org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authenticatedSubjectIdentifier_ = "";

        federatedIdPName_ = "";

        isFederatedUser_ = false;

        tenantDomain_ = "";

        userStoreDomain_ = "";

        userName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_User_descriptor;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.User getDefaultInstanceForType() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.User build() {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.User buildPartial() {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.User result = new org.wso2.custom.authenticator.local.grpc.UserOuterClass.User(this);
        result.authenticatedSubjectIdentifier_ = authenticatedSubjectIdentifier_;
        result.federatedIdPName_ = federatedIdPName_;
        result.isFederatedUser_ = isFederatedUser_;
        result.tenantDomain_ = tenantDomain_;
        result.userStoreDomain_ = userStoreDomain_;
        result.userName_ = userName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.custom.authenticator.local.grpc.UserOuterClass.User) {
          return mergeFrom((org.wso2.custom.authenticator.local.grpc.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.custom.authenticator.local.grpc.UserOuterClass.User other) {
        if (other == org.wso2.custom.authenticator.local.grpc.UserOuterClass.User.getDefaultInstance()) return this;
        if (!other.getAuthenticatedSubjectIdentifier().isEmpty()) {
          authenticatedSubjectIdentifier_ = other.authenticatedSubjectIdentifier_;
          onChanged();
        }
        if (!other.getFederatedIdPName().isEmpty()) {
          federatedIdPName_ = other.federatedIdPName_;
          onChanged();
        }
        if (other.getIsFederatedUser() != false) {
          setIsFederatedUser(other.getIsFederatedUser());
        }
        if (!other.getTenantDomain().isEmpty()) {
          tenantDomain_ = other.tenantDomain_;
          onChanged();
        }
        if (!other.getUserStoreDomain().isEmpty()) {
          userStoreDomain_ = other.userStoreDomain_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.custom.authenticator.local.grpc.UserOuterClass.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object authenticatedSubjectIdentifier_ = "";
      /**
       * <code>string authenticatedSubjectIdentifier = 1;</code>
       */
      public java.lang.String getAuthenticatedSubjectIdentifier() {
        java.lang.Object ref = authenticatedSubjectIdentifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authenticatedSubjectIdentifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthenticatedSubjectIdentifierBytes() {
        java.lang.Object ref = authenticatedSubjectIdentifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authenticatedSubjectIdentifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 1;</code>
       */
      public Builder setAuthenticatedSubjectIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authenticatedSubjectIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 1;</code>
       */
      public Builder clearAuthenticatedSubjectIdentifier() {
        
        authenticatedSubjectIdentifier_ = getDefaultInstance().getAuthenticatedSubjectIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>string authenticatedSubjectIdentifier = 1;</code>
       */
      public Builder setAuthenticatedSubjectIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authenticatedSubjectIdentifier_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object federatedIdPName_ = "";
      /**
       * <code>string federatedIdPName = 2;</code>
       */
      public java.lang.String getFederatedIdPName() {
        java.lang.Object ref = federatedIdPName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          federatedIdPName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string federatedIdPName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFederatedIdPNameBytes() {
        java.lang.Object ref = federatedIdPName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          federatedIdPName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string federatedIdPName = 2;</code>
       */
      public Builder setFederatedIdPName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        federatedIdPName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string federatedIdPName = 2;</code>
       */
      public Builder clearFederatedIdPName() {
        
        federatedIdPName_ = getDefaultInstance().getFederatedIdPName();
        onChanged();
        return this;
      }
      /**
       * <code>string federatedIdPName = 2;</code>
       */
      public Builder setFederatedIdPNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        federatedIdPName_ = value;
        onChanged();
        return this;
      }

      private boolean isFederatedUser_ ;
      /**
       * <code>bool isFederatedUser = 3;</code>
       */
      public boolean getIsFederatedUser() {
        return isFederatedUser_;
      }
      /**
       * <code>bool isFederatedUser = 3;</code>
       */
      public Builder setIsFederatedUser(boolean value) {
        
        isFederatedUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFederatedUser = 3;</code>
       */
      public Builder clearIsFederatedUser() {
        
        isFederatedUser_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object tenantDomain_ = "";
      /**
       * <code>string tenantDomain = 4;</code>
       */
      public java.lang.String getTenantDomain() {
        java.lang.Object ref = tenantDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantDomain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tenantDomain = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTenantDomainBytes() {
        java.lang.Object ref = tenantDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tenantDomain = 4;</code>
       */
      public Builder setTenantDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tenantDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tenantDomain = 4;</code>
       */
      public Builder clearTenantDomain() {
        
        tenantDomain_ = getDefaultInstance().getTenantDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string tenantDomain = 4;</code>
       */
      public Builder setTenantDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tenantDomain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userStoreDomain_ = "";
      /**
       * <code>string userStoreDomain = 5;</code>
       */
      public java.lang.String getUserStoreDomain() {
        java.lang.Object ref = userStoreDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userStoreDomain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userStoreDomain = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserStoreDomainBytes() {
        java.lang.Object ref = userStoreDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userStoreDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userStoreDomain = 5;</code>
       */
      public Builder setUserStoreDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userStoreDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userStoreDomain = 5;</code>
       */
      public Builder clearUserStoreDomain() {
        
        userStoreDomain_ = getDefaultInstance().getUserStoreDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string userStoreDomain = 5;</code>
       */
      public Builder setUserStoreDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userStoreDomain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 6;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 6;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 6;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 6;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final org.wso2.custom.authenticator.local.grpc.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.custom.authenticator.local.grpc.UserOuterClass.User();
    }

    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.custom.authenticator.local.grpc.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string role = 1;</code>
     */
    java.lang.String getRole();
    /**
     * <code>string role = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoleBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      role_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              role_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.class, org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.Builder.class);
    }

    public static final int ROLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object role_;
    /**
     * <code>string role = 1;</code>
     */
    public java.lang.String getRole() {
      java.lang.Object ref = role_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        role_ = s;
        return s;
      }
    }
    /**
     * <code>string role = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRoleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, role_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRoleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, role_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response)) {
        return super.equals(obj);
      }
      org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response other = (org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response) obj;

      boolean result = true;
      result = result && getRole()
          .equals(other.getRole());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRole().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.class, org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.Builder.class);
      }

      // Construct using org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        role_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response getDefaultInstanceForType() {
        return org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response build() {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response buildPartial() {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response result = new org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response(this);
        result.role_ = role_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response) {
          return mergeFrom((org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response other) {
        if (other == org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response.getDefaultInstance()) return this;
        if (!other.getRole().isEmpty()) {
          role_ = other.role_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object role_ = "";
      /**
       * <code>string role = 1;</code>
       */
      public java.lang.String getRole() {
        java.lang.Object ref = role_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          role_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string role = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoleBytes() {
        java.lang.Object ref = role_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          role_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string role = 1;</code>
       */
      public Builder setRole(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        role_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string role = 1;</code>
       */
      public Builder clearRole() {
        
        role_ = getDefaultInstance().getRole();
        onChanged();
        return this;
      }
      /**
       * <code>string role = 1;</code>
       */
      public Builder setRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        role_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response();
    }

    public static org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.custom.authenticator.local.grpc.UserOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"\242\001\n\004User\022&\n\036authenticatedSu" +
      "bjectIdentifier\030\001 \001(\t\022\030\n\020federatedIdPNam" +
      "e\030\002 \001(\t\022\027\n\017isFederatedUser\030\003 \001(\010\022\024\n\014tena" +
      "ntDomain\030\004 \001(\t\022\027\n\017userStoreDomain\030\005 \001(\t\022" +
      "\020\n\010userName\030\006 \001(\t\"\030\n\010Response\022\014\n\004role\030\001 " +
      "\001(\t2)\n\004user\022!\n\013getRoleName\022\005.User\032\t.Resp" +
      "onse\"\000B*\n(org.wso2.custom.authenticator." +
      "local.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "AuthenticatedSubjectIdentifier", "FederatedIdPName", "IsFederatedUser", "TenantDomain", "UserStoreDomain", "UserName", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Role", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
